var markMass = 78;
var markHeight = 1.69;
var johnMass = 92;
var johnHeight = 1.95;
var markBMI = markMass / Math.pow(markHeight, 2);
var johnBMI = johnMass / Math.pow(johnHeight, 2);
var markHigherBMI = markBMI > johnBMI;
console.log(markBMI, johnBMI, markHigherBMI);
var markMass2 = 95;
var markHeight2 = 1.88;
var johnMass2 = 85;
var johnHeight2 = 1.76;
var markBMI2 = markMass2 / Math.pow(markHeight2, 2);
var johnBMI2 = johnMass2 / Math.pow(johnHeight2, 2);
var markHigherBMI2 = markBMI2 > johnBMI2;
console.log(markBMI2, johnBMI2, markHigherBMI2);
